export const styleConst = {
  // 页面背景默认
  "background-default": "#F6F8FB",
  "background-hovered": "#CCCED1",
  "background-highlight": "#D6E4FF",
  "background-primary": "#3366ff",
  "background-white": "#FFFFFF",
  // 卡片背景
  "surface-default": "#FFFFFF",
  "surface-subdued": "#F6F6F9",
  "surface-hovered": "#F0F0F4",
  "surface-pressed": "#EEEEF2",
  "surface-selected": "#E6E6EF",
  /// 文字
  "text-default": "#25435F",
  "text-subdued": "#909DAA",
  "text-disabled": "#DCE1E5",
  "text-lose": "#AFB8C5",
  "text-bright": "#FF6262",
  // 文字状态
  "text-success": "#2FDD7F",
  "text-warning": "#C7A10A",
  "text-fail": "#FF6262",
  // border
  "border-default": "#ddddea",
  "border-subdued": "#ebedf0",
  "border-disabled": "#BFC6D3",
  // Icon
  "icon-default": "#25435F",
  "icon-subdued": "#A0A0B0",
  "icon-hovered": "#383852",
  "icon-pressed": "#4B4B63",
  "icon-disabled": "#D4D4DD",
  // action状态
  "action-primary-default": "#3366ff",
  "action-primary-hovered": "#3366ff",
  // 遮罩
  backdrop: "#00235299",
  // 分割线
  divider: "#F3F3F6",
  // 阴影
  shadow: "#E4E8FA",
};
